FROM node:22-alpine
RUN npm install -g pnpm
WORKDIR /src/app

COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./backend ./backend
COPY ./prisma ./prisma
RUN pnpm install
RUN pnpm prisma generate
EXPOSE 3000

CMD ["pnpm", "run", "dev:migrate"]
