on:
    push:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        # Checkout the repository
        - name: Checking out the code
          uses: actions/checkout@v2
  
        # Docker login to Docker Hub
        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUBUSERNAME }}
            password: ${{ secrets.DOCKERHUBTOKEN }}
  
        # Build and push Docker image to Docker Hub
        - name: Build and push to Docker Hub    
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./docker/Dockerfile.backend
            push: true
            tags: alexgoot/backend:${{ github.sha }}
  
        # Deploy to the VM via SSH
        - name: Deploy to the VM
          run: |
            # Save the SSH private key from GitHub secrets to a file
            echo "${{ secrets.SSHKEY }}" > ~/ssh_key
  
            # Set correct file permissions for the SSH key
            chmod 600 ~/ssh_key
  
            # SSH to the VM and stop/remove the old container, then run the new container
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.203.207.90 -t <<EOF
              # Stop and remove the existing container (if any)
              docker stop user_backend || true
              docker rm user_backend || true
  
              # Run the new container with environment variables
              docker run -d \
                -p 3000:3000 \
                -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                -e SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" \
                -e TEMPLATE_ID="${{ secrets.TEMPLATE_ID }}" \
                --name user_backend \
                --network erp-network \
                alexgoot/backend:${{ github.sha }}
            EOF
  