on:
 push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out the code
              uses: actions/checkout@v2

            - name: docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUBUSERNAME }}
                password: ${{ secrets.DOCKERHUBTOKEN }}
            - name: Build and push to dockerhub    
              uses: docker/build-push-action@v4
              with:
                context:
                file: ./docker/Dockerfile.backend
                push: true    
                tags: alexgoot/backend:${{github.sha}}
            - name: Deploy to the VM
              run: |
                echo "${{ secrets.SSHKEY }}" &> ~/ssh_key
                chmod 700 /home/runner/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@13.203.207.90 -t "docker stop user_backend && docker run --name user_backend -d -p 3000:3000 alexgoot/backend:${{ github.sha }}"    
