on:
 push:
jobs:
    build:
        runs-on: ubuntu_latest
        steps:
            - name: Checking out the code
              uses: action/checkout@v2

            - name: docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUBUSERNAME }}
                password: ${{ secrets.DOCKERHUBTOKEN }}
            - name: Build and push to dockerhub    
              uses: docker/build-push-action@v4
              with:
                context:
                file: ./docker/Dockerfile.backend
                push: true    
                tags: ERP/backend:${{github.sha}}
